In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
import time
import sys

In [7]:
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [8]:
c=np.arange(1000)
print(c.size*c.itemsize)

8000


In [9]:
size=10000

In [10]:
L1=range(size)


In [11]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
#get dim
a.ndim

1

In [15]:
b.ndim

2

In [16]:
#get shape
b.shape

(2, 3)

In [17]:
a.shape

(3,)

In [18]:
#get type
a.dtype

dtype('int64')

In [19]:
#get size
a.itemsize

8

In [20]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#get a spesific element [r,c]
a[1,5]

13

In [22]:
#get spesific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#get spesific column
a[:,2]

array([ 3, 10])

In [24]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [26]:
a[1,5]=20
print(a)

a[:,2]=5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [27]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
#get spesific element (work outside in)
b[0,1,1]

4

In [32]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [31]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
#all o matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [36]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [37]:
#random decimal numbers
np.random.rand(4,2)

array([[0.7708256 , 0.92144992],
       [0.17216409, 0.05113566],
       [0.20567982, 0.1967029 ],
       [0.66348154, 0.58885809]])

In [39]:
#random integer values
np.random.randint(7,size=(3,3))

array([[2, 2, 5],
       [5, 2, 3],
       [5, 6, 3]])

In [40]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
a+2

array([3, 4, 5, 6])

In [42]:
a-2

array([-1,  0,  1,  2])

In [43]:
a*2

array([2, 4, 6, 8])

In [45]:
a=np.ones((2,3))

In [46]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
b=np.full((3,2),2)

In [48]:
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [49]:
c=np.identity(3)
np.linalg.det(c)

1.0